version: "3.3"

services:
  nextjs:
    ports:
      - 3001:3001
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nextjs-image
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next